/**
 * Dummy appointment data for admin Calendar and Programări (no API yet).
 */

export type DummyAppointmentStatus = "Confirmat" | "În așteptare";
export type DummyAppointmentType = "general" | "tyre" | "carWash";

export interface DummyAppointment {
  id: string;
  nume: string;
  telefon: string;
  email: string;
  data: string;
  ora: string;
  marca: string;
  model: string;
  tip: DummyAppointmentType;
  status: DummyAppointmentStatus;
  descriere?: string;
}

export const DUMMY_APPOINTMENTS: DummyAppointment[] = [
  // Istoric (trecute)
  {
    id: "h1",
    nume: "Constantin Dragomir",
    telefon: "0721 100 200",
    email: "constantin.d@email.ro",
    data: "5 Jan 2025",
    ora: "09:00",
    marca: "Audi",
    model: "A4",
    tip: "general",
    status: "Confirmat",
    descriere: "Revizie",
  },
  {
    id: "h2",
    nume: "Simona Florea",
    telefon: "0732 200 300",
    email: "simona.f@email.ro",
    data: "10 Jan 2025",
    ora: "11:00",
    marca: "Peugeot",
    model: "308",
    tip: "tyre",
    status: "Confirmat",
    descriere: "Schimb anvelope iarnă",
  },
  {
    id: "h3",
    nume: "Adrian Cojocaru",
    telefon: "0743 300 400",
    email: "adrian.c@email.ro",
    data: "15 Jan 2025",
    ora: "14:00",
    marca: "Honda",
    model: "Civic",
    tip: "carWash",
    status: "Confirmat",
    descriere: "Spălare + ceră",
  },
  {
    id: "h4",
    nume: "Raluca Dumitrescu",
    telefon: "0754 400 500",
    email: "raluca.d@email.ro",
    data: "28 Jan 2025",
    ora: "10:30",
    marca: "Kia",
    model: "Ceed",
    tip: "general",
    status: "Confirmat",
    descriere: "Diagnoză",
  },
  {
    id: "h5",
    nume: "Florin Enache",
    telefon: "0765 500 600",
    email: "florin.e@email.ro",
    data: "3 Feb 2025",
    ora: "08:00",
    marca: "Nissan",
    model: "Qashqai",
    tip: "tyre",
    status: "Confirmat",
    descriere: "Echilibrare",
  },
  {
    id: "h6",
    nume: "Gabriela Filip",
    telefon: "0776 600 700",
    email: "gabriela.f@email.ro",
    data: "8 Feb 2025",
    ora: "15:00",
    marca: "Mercedes",
    model: "C-Class",
    tip: "carWash",
    status: "Confirmat",
    descriere: "Detailing interior",
  },
  // Viitoare / curente
  {
    id: "1",
    nume: "Maria Popescu",
    telefon: "0722 111 222",
    email: "maria.popescu@email.ro",
    data: "12 Feb 2025",
    ora: "09:00",
    marca: "VW",
    model: "Golf VII",
    tip: "general",
    status: "Confirmat",
    descriere: "Revizie periodică",
  },
  {
    id: "2",
    nume: "Ion Ionescu",
    telefon: "0733 222 333",
    email: "ion.ionescu@email.ro",
    data: "12 Feb 2025",
    ora: "11:30",
    marca: "Dacia",
    model: "Duster",
    tip: "tyre",
    status: "În așteptare",
    descriere: "Schimb anvelope",
  },
  {
    id: "3",
    nume: "Elena Marin",
    telefon: "0744 333 444",
    email: "elena.marin@email.ro",
    data: "13 Feb 2025",
    ora: "10:00",
    marca: "BMW",
    model: "320d",
    tip: "general",
    status: "Confirmat",
    descriere: "Diagnoză motor",
  },
  {
    id: "4",
    nume: "Andrei Stan",
    telefon: "0755 444 555",
    email: "andrei.stan@email.ro",
    data: "13 Feb 2025",
    ora: "14:00",
    marca: "Skoda",
    model: "Octavia",
    tip: "general",
    status: "În așteptare",
    descriere: "Frâne",
  },
  {
    id: "5",
    nume: "Cristina Radu",
    telefon: "0766 555 666",
    email: "cristina.radu@email.ro",
    data: "14 Feb 2025",
    ora: "09:00",
    marca: "Ford",
    model: "Focus",
    tip: "carWash",
    status: "Confirmat",
    descriere: "Spălare exterior + interior",
  },
  {
    id: "6",
    nume: "Mihai Dobre",
    telefon: "0777 666 777",
    email: "mihai.dobre@email.ro",
    data: "14 Feb 2025",
    ora: "15:30",
    marca: "Renault",
    model: "Megane",
    tip: "tyre",
    status: "În așteptare",
    descriere: "Echilibrare roți",
  },
  {
    id: "7",
    nume: "Ana Popa",
    telefon: "0788 777 888",
    email: "ana.popa@email.ro",
    data: "15 Feb 2025",
    ora: "08:00",
    marca: "Toyota",
    model: "Corolla",
    tip: "general",
    status: "Confirmat",
    descriere: "Revizie",
  },
  {
    id: "8",
    nume: "Vasile Munteanu",
    telefon: "0799 888 999",
    email: "vasile.m@email.ro",
    data: "15 Feb 2025",
    ora: "12:00",
    marca: "Hyundai",
    model: "i30",
    tip: "tyre",
    status: "În așteptare",
    descriere: "Montaj anvelope vara",
  },
  {
    id: "9",
    nume: "Ioana Vasilescu",
    telefon: "0711 999 000",
    email: "ioana.v@email.ro",
    data: "16 Feb 2025",
    ora: "09:30",
    marca: "Opel",
    model: "Astra",
    tip: "carWash",
    status: "Confirmat",
    descriere: "Detailing complet",
  },
  {
    id: "10",
    nume: "George Niculescu",
    telefon: "0722 000 111",
    email: "george.n@email.ro",
    data: "16 Feb 2025",
    ora: "14:00",
    marca: "Volvo",
    model: "V60",
    tip: "general",
    status: "În așteptare",
    descriere: "Înlocuire placute frâne",
  },
  {
    id: "11",
    nume: "Daniela Ionescu",
    telefon: "0733 111 222",
    email: "daniela.i@email.ro",
    data: "17 Feb 2025",
    ora: "10:00",
    marca: "Seat",
    model: "Leon",
    tip: "tyre",
    status: "Confirmat",
    descriere: "Geometrie roți",
  },
  {
    id: "12",
    nume: "Stefan Pop",
    telefon: "0744 222 333",
    email: "stefan.pop@email.ro",
    data: "17 Feb 2025",
    ora: "15:00",
    marca: "Mazda",
    model: "3",
    tip: "carWash",
    status: "În așteptare",
    descriere: "Spălare exterior",
  },
  {
    id: "13",
    nume: "Laura Ionescu",
    telefon: "0755 333 444",
    email: "laura.i@email.ro",
    data: "20 Feb 2025",
    ora: "09:00",
    marca: "VW",
    model: "Polo",
    tip: "general",
    status: "În așteptare",
    descriere: "Revizie",
  },
  {
    id: "14",
    nume: "Bogdan Stan",
    telefon: "0766 444 555",
    email: "bogdan.s@email.ro",
    data: "20 Feb 2025",
    ora: "13:00",
    marca: "Ford",
    model: "Puma",
    tip: "tyre",
    status: "Confirmat",
    descriere: "Montaj anvelope",
  },
  {
    id: "15",
    nume: "Claudia Manea",
    telefon: "0777 555 666",
    email: "claudia.m@email.ro",
    data: "25 Feb 2025",
    ora: "10:30",
    marca: "Fiat",
    model: "500",
    tip: "carWash",
    status: "În așteptare",
    descriere: "Spălare",
  },
  {
    id: "16",
    nume: "Radu Popescu",
    telefon: "0788 666 777",
    email: "radu.p@email.ro",
    data: "2 Mar 2025",
    ora: "11:00",
    marca: "Skoda",
    model: "Fabia",
    tip: "general",
    status: "Confirmat",
    descriere: "Frâne + verificare",
  },
  {
    id: "17",
    nume: "Monica Dinu",
    telefon: "0799 777 888",
    email: "monica.d@email.ro",
    data: "2 Mar 2025",
    ora: "15:00",
    marca: "Renault",
    model: "Clio",
    tip: "tyre",
    status: "În așteptare",
    descriere: "Echilibrare",
  },
  {
    id: "18",
    nume: "Tudor Neagu",
    telefon: "0710 888 999",
    email: "tudor.n@email.ro",
    data: "18 Feb 2025",
    ora: "10:00",
    marca: "Citroën",
    model: "C3",
    tip: "general",
    status: "Confirmat",
    descriere: "Verificare tehnică",
  },
  {
    id: "19",
    nume: "Diana Rusu",
    telefon: "0721 999 000",
    email: "diana.r@email.ro",
    data: "22 Feb 2025",
    ora: "14:00",
    marca: "Mini",
    model: "Cooper",
    tip: "carWash",
    status: "În așteptare",
    descriere: "Detailing",
  },
  {
    id: "20",
    nume: "Alexandru Stoica",
    telefon: "0732 000 111",
    email: "alex.s@email.ro",
    data: "28 Feb 2025",
    ora: "09:30",
    marca: "Volkswagen",
    model: "Passat",
    tip: "general",
    status: "Confirmat",
    descriere: "Revizie",
  },
  {
    id: "21",
    nume: "Oana Preda",
    telefon: "0743 111 222",
    email: "oana.p@email.ro",
    data: "5 Mar 2025",
    ora: "11:00",
    marca: "Toyota",
    model: "Yaris",
    tip: "tyre",
    status: "În așteptare",
    descriere: "Schimb anvelope",
  },
  {
    id: "22",
    nume: "Mihai Voicu",
    telefon: "0754 222 333",
    email: "mihai.v@email.ro",
    data: "10 Mar 2025",
    ora: "08:00",
    marca: "Hyundai",
    model: "Tucson",
    tip: "carWash",
    status: "Confirmat",
    descriere: "Spălare completă",
  },
  {
    id: "23",
    nume: "Corina Georgescu",
    telefon: "0765 333 444",
    email: "corina.g@email.ro",
    data: "15 Mar 2025",
    ora: "10:00",
    marca: "Peugeot",
    model: "2008",
    tip: "general",
    status: "În așteptare",
    descriere: "Revizie + frâne",
  },
  {
    id: "24",
    nume: "Liviu Barbu",
    telefon: "0776 444 555",
    email: "liviu.b@email.ro",
    data: "20 Mar 2025",
    ora: "14:30",
    marca: "Ford",
    model: "Kuga",
    tip: "tyre",
    status: "Confirmat",
    descriere: "Schimb anvelope",
  },
  {
    id: "25",
    nume: "Roxana Nistor",
    telefon: "0787 555 666",
    email: "roxana.n@email.ro",
    data: "25 Mar 2025",
    ora: "09:00",
    marca: "BMW",
    model: "Serie 1",
    tip: "carWash",
    status: "În așteptare",
    descriere: "Spălare + ceră",
  },
  {
    id: "26",
    nume: "Sorin Mocanu",
    telefon: "0798 666 777",
    email: "sorin.m@email.ro",
    data: "1 Apr 2025",
    ora: "11:00",
    marca: "Dacia",
    model: "Sandero",
    tip: "general",
    status: "Confirmat",
    descriere: "Verificare tehnică",
  },
  {
    id: "27",
    nume: "Teodora Lupu",
    telefon: "0709 777 888",
    email: "teodora.l@email.ro",
    data: "5 Apr 2025",
    ora: "15:00",
    marca: "Volvo",
    model: "XC40",
    tip: "tyre",
    status: "În așteptare",
    descriere: "Echilibrare + geometrie",
  },
  {
    id: "28",
    nume: "Paul Andrei",
    telefon: "0711 888 999",
    email: "paul.a@email.ro",
    data: "12 Feb 2025",
    ora: "14:00",
    marca: "Opel",
    model: "Corsa",
    tip: "carWash",
    status: "În așteptare",
    descriere: "Spălare rapidă",
  },
  {
    id: "29",
    nume: "Irina Badea",
    telefon: "0722 999 000",
    email: "irina.b@email.ro",
    data: "13 Feb 2025",
    ora: "16:00",
    marca: "Suzuki",
    model: "Vitara",
    tip: "general",
    status: "Confirmat",
    descriere: "Diagnoză",
  },
  {
    id: "30",
    nume: "Cosmin Dima",
    telefon: "0733 000 111",
    email: "cosmin.d@email.ro",
    data: "19 Feb 2025",
    ora: "08:30",
    marca: "Kia",
    model: "Sportage",
    tip: "tyre",
    status: "Confirmat",
    descriere: "Montaj anvelope",
  },
  {
    id: "31",
    nume: "Elena Florea",
    telefon: "0744 111 222",
    email: "elena.f@email.ro",
    data: "24 Feb 2025",
    ora: "11:30",
    marca: "Honda",
    model: "HR-V",
    tip: "general",
    status: "În așteptare",
    descriere: "Revizie",
  },
  {
    id: "32",
    nume: "Andrei Gheorghe",
    telefon: "0755 222 333",
    email: "andrei.g@email.ro",
    data: "3 Mar 2025",
    ora: "13:00",
    marca: "Nissan",
    model: "Juke",
    tip: "carWash",
    status: "Confirmat",
    descriere: "Detailing",
  },
  {
    id: "33",
    nume: "Mihaela Hangan",
    telefon: "0766 333 444",
    email: "mihaela.h@email.ro",
    data: "8 Mar 2025",
    ora: "10:00",
    marca: "Mazda",
    model: "CX-5",
    tip: "general",
    status: "În așteptare",
    descriere: "Verificare",
  },
  {
    id: "34",
    nume: "Vlad Ionescu",
    telefon: "0777 444 555",
    email: "vlad.i@email.ro",
    data: "12 Mar 2025",
    ora: "15:00",
    marca: "Audi",
    model: "A3",
    tip: "tyre",
    status: "Confirmat",
    descriere: "Echilibrare",
  },
  {
    id: "35",
    nume: "Nicoleta Jitaru",
    telefon: "0788 555 666",
    email: "nicoleta.j@email.ro",
    data: "18 Mar 2025",
    ora: "09:00",
    marca: "Seat",
    model: "Arona",
    tip: "carWash",
    status: "În așteptare",
    descriere: "Spălare",
  },
  {
    id: "36",
    nume: "Bogdan Kovač",
    telefon: "0799 666 777",
    email: "bogdan.k@email.ro",
    data: "22 Mar 2025",
    ora: "14:00",
    marca: "Skoda",
    model: "Kamiq",
    tip: "general",
    status: "Confirmat",
    descriere: "Frâne",
  },
  {
    id: "37",
    nume: "Diana Lungu",
    telefon: "0710 777 888",
    email: "diana.l@email.ro",
    data: "28 Mar 2025",
    ora: "11:00",
    marca: "Renault",
    model: "Captur",
    tip: "tyre",
    status: "În așteptare",
    descriere: "Schimb anvelope",
  },
];
